### ISSUE TITLE
Cannot use responsive design of modal

### ISSUE THREAD

**Issue by J4gQBqqR** [kidonng/unocss-preset-daisy#20] opened 2023-04-15 14:55 UTC
This does not work: https://daisyui.com/components/modal/#responsive-modal-goes-bottom-on-mobile-screen-and-goes-middle-on-desktop
```
<!-- The button to open modal -->
<label for="my-modal-6" class="btn">open modal</label>

<!-- Put this part before </body> tag -->
<input type="checkbox" id="my-modal-6" class="modal-toggle" />
<div class="modal modal-bottom sm:modal-middle">
  <div class="modal-box">
    <h3 class="font-bold text-lg">Congratulations random Internet user!</h3>
    <p class="py-4">You've been selected for a chance to get one year of subscription to use Wikipedia for free!</p>
    <div class="modal-action">
      <label for="my-modal-6" class="btn">Yay!</label>
    </div>
  </div>
</div>
```
This is different from issue #19, as there is no @apply used in here. But we still do not have any responsive design working. Not sure how Unocss is limiting the responsive design in this case.

**Comment by kidonng** [comment] 2023-04-15 17:28
Duplicate of #14

**Closed by kidonng** 2023-04-15 17:28 UTC
